GET {{base_url}}/api/v1/foo
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}
Cache-Control: no-cache

### Insert foo
POST {{base_url}}/api/v1/foo
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}
Cache-Control: no-cache

{
  "name": "Foo"
}

### Update foo
PUT {{base_url}}/api/v1/foo/1
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}
Cache-Control: no-cache

{
  "name": "Baz"
}
